### ISSUE TITLE
No idea

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#25]
:29:44 WARN]: Failed to handle packet for /101.254.212.254:53078
net.minecraft.server.v1_8_R3.ReportedException: Sending packet
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:921) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.EntityPlayer.a(EntityPlayer.java:766) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.Container.addSlotListener(Container.java:59) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.EntityPlayer.syncInventory(EntityPlayer.java:174) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:174) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:813) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.LinkageError: com/comphenix/protocol/events/PacketContainer
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:277) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:415) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:381) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:349) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        ... 13 more

**Comment by dumbninja22** [comment]
Try updating ProtocolLib and Lib's Disguises
