### ISSUE TITLE
SQL disconnect Issue

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#6]
So MySQL will disconnect the connection every 8 hours by default.
If you may check the connection every 30 minutes , that will be very grateful!

or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[09:27:52 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:27:52 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[09:27:52 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:27:52 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[09:27:52 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[09:27:52 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[09:27:52 WARN]:        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3348)
[09:27:52 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1967)
[09:27:52 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[09:27:52 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[09:27:52 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1662)
[09:27:52 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1581)
[09:27:52 WARN]:        at com.dumbninja22.ultimatehidenseek.ninjagamesAPI.MySQLManager.sqlSavePlayerShopItems(MySQLManager.java:383)
[09:27:52 WARN]:        ... 12 more
[09:27:52 WARN]: Caused by: java.net.SocketException: 断开的管道
[09:27:52 WARN]:        at java.net.SocketOutputStream.socketWrite0(Native Method)
[09:27:52 WARN]:        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
[09:27:52 WARN]:        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
[09:27:52 WARN]:        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[09:27:52 WARN]:        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[09:27:52 WARN]:        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3329)
[09:27:52 WARN]:        ... 18 more

**Comment by dumbninja22** [comment]
Should be fixed in 1.4.6.
