### ISSUE TITLE
No pointer Exception Issue

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#7]
Tick loop 
None cound join.

:29 WARN]: [Ultimate_Hide_N_Seek] Task #3048 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:29 WARN]: [Ultimate_Hide_N_Seek] Task #3053 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:29 WARN]: [Ultimate_Hide_N_Seek] Task #3048 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:30 WARN]: [Ultimate_Hide_N_Seek] Task #3053 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:30 WARN]: [Ultimate_Hide_N_Seek] Task #3048 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:30 WARN]: [Ultimate_Hide_N_Seek] Task #3053 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:30 WARN]: [Ultimate_Hide_N_Seek] Task #3048 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:31 WARN]: [Ultimate_Hide_N_Seek] Task #3053 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:31 WARN]: [Ultimate_Hide_N_Seek] Task #3048 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:31 WARN]: [Ultimate_Hide_N_Seek] Task #3053 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:31 WARN]: [Ultimate_Hide_N_Seek] Task #3048 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:32 WARN]: [Ultimate_Hide_N_Seek] Task #3053 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:32 WARN]: [Ultimate_Hide_N_Seek] Task #3048 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:32 WARN]: [Ultimate_Hide_N_Seek] Task #3053 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
[06:14:32 WARN]: [Ultimate_Hide_N_Seek] Task #3048 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException

**Comment by JHXSMatthew** [comment]
New:
This happens after one game finish and  all players are sent to lobby.

**Comment by dumbninja22** [comment]
Who is hosting your server?

**Comment by JHXSMatthew** [comment]
It's a dedicated server. 
Running under CentOS 6.5
It's my own server.

**Comment by dumbninja22** [comment]
OK so I suspect that some system is hiding the full error to save disk space. It could be Linux command prompt that works like that.

So I suggest you try to find the first time this error appears and it should be a full error.

**Comment by JHXSMatthew** [comment]
[11:03:57] [Server thread/WARN]: [Ultimate_Hide_N_Seek] Task #1408 for Ultimate_Hide_N_Seek v1.4.5 generated an exception
java.lang.NullPointerException
        at com.dumbninja22.ultimatehidenseek.ninjagamesAPI.Utils.removeFromBoard(Utils.java:50) ~[?:?]
        at com.dumbninja22.ultimatehidenseek.ninjagamesAPI.IScoreboardManager$2.run(IScoreboardManager.java:137) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by JHXSMatthew** [comment]
Cat it !

**Comment by JHXSMatthew** [comment]
Maybe you remove player after they leave the server ?

**Comment by dumbninja22** [comment]
Ah ha! Perfect! A scoreboard issue.

**Comment by dumbninja22** [comment]
Should be fixed in 1.4.6.
